### ISSUE TITLE
Vulnerabilidad en versión Django

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/sifos#11]
Github reporta problemas de seguridad con la versión de Django (Django==1.11.5). Existe alguna buena razón para no usar una versión más reciente (>2.0)? Si no, por favor actualizar la vesión de Django.

![screenshot_2018-11-05 crear incidencias para entregables issue 10 jmencisom sifos](https://user-images.githubusercontent.com/1332546/48034235-891d2780-e12c-11e8-9b60-bcb0605681d2.png)

Gracias.

**Comment by ClareRodri** [comment]
La versión 1.11 de Django es la última compatible con la versión 2.7 de Python. En caso de requerir (por necesidad del proceso de desarrollo) la versión estable 2.7 de Python el proyecto generado en Django no se vería afectado.

Se evaluará con el equipo de desarrollo la posibilidad de realizar la actualización. 
Gracias.

**Comment by diegoasencio96** [comment]
¿y la version 1.11.15 reporta la misma vulnerabilidad?

**Comment by jmencisom** [comment]
Actualmente, github reporta https://github.com/jmencisom/sifos/network/alerts

**Comment by diegoasencio96** [comment]
Si todos estamos de acuerdo en realizar la migración a django 2 yo podria ayudar en esa parte.

**Comment by MikeSoft** [comment]
A estas alturas, cambiar la versión puede ser tedioso para el equipo de backend. ya que podría tener varios traumatismos por los cambios.

**Comment by diegoasencio96** [comment]
Ya se actualizo la version de django.
