### ISSUE TITLE
¿Repositorio para App?

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/sifos#13]
¿Se debe crear otro repositorio para la aplicación móvil de financiación colectiva?

Gracias.

**Comment by ClareRodri** [comment]
El versionamiento de la app móvil se realiza en el mismo repositorio pero en otro directorio.  Esto con el fin de tener las ultimas versiones compatibles (entre si) y al día del proyecto web y app móvil

**Comment by jmencisom** [comment]
Gracias Clarena por la aclaración, sin embargo me queda la duda sobre cómo hacer integración continua con 2 aplicaciónes (Ej: proyecto web y app móvil). Esperemos a ver cómo evolucionan los proyectos.

**Comment by charles7aponteunillanos** [comment]
> El versionamiento de la app móvil se realiza en el mismo repositorio pero en otro directorio. Esto con el fin de tener las ultimas versiones compatibles (entre si) y al día del proyecto web y app móvil

tener todo en mismo repor no es garantia que todos esten en la misma version , lo mejor es tener 3 repositorios para que permita independencia, y cada repor tiene su manejo de version.

**Comment by FelipeIzquierdo** [comment]
Buen dia, lo ideal es tener un repo por proyecto y una wiki  que referencie todo el proyecto completo, tener repo para back, repo para front y repo para móvil, de lo contrario no se puede integrar CI y es una pésima practica tener todo mezclado

**Comment by jmencisom** [comment]
¿Qué tecnología usará el front?

**Comment by FelipeIzquierdo** [comment]
jquery y bootstrap

**Comment by jmencisom** [comment]
https://github.com/jmencisom/sifos-app/

**Comment by jmencisom** [comment]
Me queda la duda si se requiere un repo adicional para el front ya que jquery y bootstrap se pueden usar con las plantillas de Django.

Por favor me confirman si el frontend usará la API como una aplicación externa o se contruirá a partir de las plantillas de Django como una aplicación interna. En el primer caso si se requiere del repo adicional.

Gracias.

**Comment by diegoasencio96** [comment]
> Me queda la duda si se requiere un repo adicional para el front ya que jquery y bootstrap se pueden usar con las plantillas de Django.
> 
> Por favor me confirman si el frontend usará la API como una aplicación externa o se contruirá a partir de las plantillas de Django como una aplicación interna. En el primer caso si se requiere del repo adicional.
> 
> Gracias.

Pensaria q sin otro repo para el front... todo dentro del mismo django y los statics en Amazon S3.
