### ISSUE TITLE
Reportar notas del segundo avance

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/sifos#37]
Reportar notas del segundo avance

**Comment by jmencisom** [comment]
[notas-segundo-avance.pdf](https://github.com/jmencisom/sifos/files/2576559/notas-segundo-avance.pdf)

**Comment by alejo1331** [comment]
Gracias Ingeniero!!!

**Comment by jmencisom** [comment]
Con gusto. Recuerden que el archivo de notas tambíen está en https://github.com/jmencisom/sifos/wiki
