### ISSUE TITLE
Configuración de webhook del respositorio

### ISSUE THREAD

**Issue by MikeSoft** [jmencisom/sifos#46]
Cordial saludo profesor.

En el siguiente mensaje se expresa el siguiente requerimiento:
Automatizar el despliegue. 

Para esto, necesitamos que desde la pestaña de webhook agregar el siguiente link:
http://138.197.73.157:8080/github-webhook/

Por favor , agrega la siguiente llave pública:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfBmz4JyjRkLyIWvwpplUHwzZXGyCVQz19bxCC2xeNkk4cPB+7xyOwXiTfpebZ8jTXZI1Q9lz5JhBajlXhGqLJ64KO2Ov/N8Cksf6V7Ct1Hm3WBlKQBXaYkyL3OJG5g6kmHvvnDc1saH6hjWkYL1PCGTCWsJQDxpfpGYEHIJkoZX2o9iaLlbCl9t2rYGf47XtLIeUMttM3a84trX4imFV49Zvc9dRAZd6CBHIW+SWgzgQCsAsV5geNJCjyekMrb82Z+jzUJsvFGEmaUNCaE0C+QDf4Hh2gSu/qXB6T13spXcdR6MJnelQiJigtEM421VxEerS2IjjF4ecKHbrdgwm1 root@farm

¡Saludos a sus estudiantes!

Referencia:
https://medium.com/@marc_best/trigger-a-jenkins-build-from-a-github-push-b922468ef1ae

**Comment by jmencisom** [comment]
![screenshot_2018-11-17 jmencisom sifos](https://user-images.githubusercontent.com/1332546/48660382-bb812b80-ea2e-11e8-97d4-0e4c4a8f1770.png)

**Comment by jmencisom** [comment]
![screenshot_2018-11-17 jmencisom sifos 1](https://user-images.githubusercontent.com/1332546/48660409-f84d2280-ea2e-11e8-92b0-68966a16c448.png)

**Comment by jmencisom** [comment]
https://dzone.com/articles/adding-a-github-webhook-in-your-jenkins-pipeline
